// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ1fPmcLl5bGJHyBULRb8zQVESMA_n73c',
    appId: '1:813850872717:web:92d119e0430dbf96fbcbc4',
    messagingSenderId: '813850872717',
    projectId: 'givelink-3393b',
    authDomain: 'givelink-3393b.firebaseapp.com',
    storageBucket: 'givelink-3393b.firebasestorage.app',
    measurementId: 'G-TZWXYQZV6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBis1WFjX6ZDMwD_kBrzAr91A-dL60SJB8',
    appId: '1:813850872717:android:34e807b6af2c9adcfbcbc4',
    messagingSenderId: '813850872717',
    projectId: 'givelink-3393b',
    storageBucket: 'givelink-3393b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm37yFZBysxUbyTUwEUbTw3jeb_3SxY2s',
    appId: '1:813850872717:ios:99f02352f3ae90d9fbcbc4',
    messagingSenderId: '813850872717',
    projectId: 'givelink-3393b',
    storageBucket: 'givelink-3393b.firebasestorage.app',
    iosBundleId: 'com.example.givelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm37yFZBysxUbyTUwEUbTw3jeb_3SxY2s',
    appId: '1:813850872717:ios:99f02352f3ae90d9fbcbc4',
    messagingSenderId: '813850872717',
    projectId: 'givelink-3393b',
    storageBucket: 'givelink-3393b.firebasestorage.app',
    iosBundleId: 'com.example.givelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ1fPmcLl5bGJHyBULRb8zQVESMA_n73c',
    appId: '1:813850872717:web:88fb35aaef189c57fbcbc4',
    messagingSenderId: '813850872717',
    projectId: 'givelink-3393b',
    authDomain: 'givelink-3393b.firebaseapp.com',
    storageBucket: 'givelink-3393b.firebasestorage.app',
    measurementId: 'G-EL9KRRZTTK',
  );
}
